export const PROGRESS_BAR_COLOR = '#28343b'
export const DRAWER_ITEM_TEXT_COLOLR = '#bec2c4'
export const DRAWER_ITEM_SELECTED_TEXT_COLOLR = '#3b80fc'
export const DRAWER_ITEM_COLOR = '#28343b'
export const DRAWER_ITEM_SEPERATOR_COLOR = '#687075';
export const LIST_BACKGROUND_COLOR = '#E0DDDD';
export const BUTTON_TEXT_COLOR = '#FFFFFF';
export const BUTTON_BACKGROUND_COLOR = '#3b80fc';
// export const COINTIKO_HEADER_COLOR = '#3b80fc';
// export const COINTIKO_HEADER_COLOR = '#28343b';
export const COINTIKO_HEADER_COLOR = '#e9eaeb';
// export const COINTIKO_STATUSBAR_COLOR = '#2959b0';
export const COINTIKO_STATUSBAR_COLOR = '#181f23';
// export const COINTIKO_HEADER_TINT_COLOR = '#ffc600';
export const COINTIKO_HEADER_TINT_COLOR = '#000';